version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew jar
artifacts:
  files:
    - samTemplate.yaml
    - build/libs/alert-lambda-1.0-SNAPSHOT.jar