AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.epam.alert.AlertRequestHandler::handleRequest'
      Runtime: java8
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::377991254608:role/service-role/someRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: POST
